### ISSUE TITLE
Add CMS v13 compatibility

### ISSUE THREAD

**Issue by agendartobias** [georgringer/extbase_with_no_l10n_parent#10]
It would be great to have a version, which is compatible with the upcoming TYPO3 CMS v13. Are there any plans?

Thank you for your effort!!!

**Comment by georgringer** [comment]
in theory this should be fixed with https://review.typo3.org/c/Packages/TYPO3.CMS/+/82087 which has also been merged to v12

**Comment by agendartobias** [comment]
Hey, you are right! I deleted this extension on our v12 instance that is problematic and everything works ok!

**Comment by georgringer** [comment]
awesome, thanks for your feedback!
