### ISSUE TITLE
LanguageMenu shows links to not available translations

### ISSUE THREAD

**Issue by web2date** [georgringer/extbase_with_no_l10n_parent#2]
Its working like a charm but...

TYPO3 10.4.8, Bootstrap Package

Siteconfiguration with 3 languages: Default DE, EN, NL ->Strict

News is only available in NL, but the language Menu shows links to the not created News in Default DE and EN 

Is this a misconfiguration of my part or a bug?

**Comment by georgringer** [comment]
this is a missing feature in news or bug in typo3 in general so you did nothing wrong. if you need such thing, maybe wanna contact me for sponsoring that
